[package]
name = "watchcat-service"
version = "1.1.0"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2021"

[dependencies]
clap = { version = "3.0", features = ["derive", "env"] }
log = "0.4"
simple_logger = {version = "1.11", default-features = false }
uptime_lib = "0.2.1"
dns-lookup = "1.0"
humantime = "2.1"
url = "2.2"
ureq = "2.4"

[profile.release]
opt-level = 'z' # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'
