[package]
name = "watchcat-service"
version = "1.0.0"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2018"

[dependencies]
structopt = { version = "0.3", default-features = false }
log = "0.4"
simple_logger = {version = "1.11", default-features = false }
futures = "0.3"
uptime_lib = "0.2.1"
dns-lookup = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
tokio = "0.3"
humantime = "2.0"
url = "2.1"
http = "0.2"

[profile.release]
opt-level = 'z' # Optimize for size.
lto = true
codegen-units = 1
panic = 'abort'
