[package]
name = "watchcat-service"
version = "1.2.1"
authors = ["Tobias Tangemann <tobias@tangemann.org>"]
edition = "2021"

[dependencies]
clap = { version = "^3.2", features = ["derive", "env"] }
log = "^0.4"
simple_logger = {version = "^2.1", default-features = false }
uptime_lib = "^0.2.1"
dns-lookup = "^1.0"
humantime = "^2.1"
url = "^2.2"
ureq = { version = "^2.4", default-features = false, features = ["native-tls"] }
native-tls = "^0.2"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
