runtime: python27
api_version: 1
threadsafe: yes

automatic_scaling:
  standard_scheduler_settings:
    max_instances: 1

handlers:
- url: /(.*\.(html|ico|png|jpg|gif|txt|js|css))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif|txt|js|css))

- url: /job
  script: jobhandler.app

- url: /cron/.*
  script: cron.app
  login: admin # secure cronjobs (no access for normal user)

- url: /task
  script: TaskQueue.app
  login: admin # secure cronjobs (no access for normal user)

- url: /log/(\w+)
  script: LogHandler.app
  login: admin # secure

- url: .*
  script: main.app
  login: admin # secure


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
