runtime: python27
api_version: 1
threadsafe: yes

# Use automatic scaling to get 28 frontend instance hours
# https://cloud.google.com/appengine/docs/standard/python/how-instances-are-managed?hl=de#instance_scaling
automatic_scaling:
  target_throughput_utilization: 0.95
  target_cpu_utilization: 0.95
  max_pending_latency: 5s
  max_instances: 1

skip_files:
  - deploy.sh
  
handlers:
- url: /(.*\.(html|ico|png|jpg|gif|txt|js|css))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif|txt|js|css))

- url: /job
  script: jobhandler.app

- url: /cron/.*
  script: cron.app
  login: admin # secure cronjobs (no access for normal user)

- url: /task
  script: TaskQueue.app
  login: admin # secure cronjobs (no access for normal user)

- url: /log/(\w+)
  script: LogHandler.app
  login: admin # secure

- url: .*
  script: main.app
  login: admin # secure


libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest
