application: watch-cat
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /(.*\.(html|ico|png|jpg|gif))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif))

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /job/(\w*)
  script: jobhandler.app

- url: .*
  script: main.app
  login: admin # secure


libraries:
- name: webapp2
  version: "2.5.2"