application: watch-cat
version: testing
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /jquery/
  static_dir: jquery/

- url: /(.*\.(html|ico|png|jpg|gif|txt))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif|txt))

- url: /job/(\w*)
  script: jobhandler.app

- url: /cron/.*
  script: cron.app
  login: admin # secure cronjobs (no access for normal user)

- url: /task
  script: TaskQueue.app
  login: admin # secure cronjobs (no access for normal user)

- url: .*
  script: main.app
  login: admin # secure


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest